on:
  push:
    branches:
      - "main"
    paths:
      - "container/**"
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build-container:
    runs-on: ubuntu-latest
    environment: "production"
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - id: repository
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{github.repository}}

      - run: docker build container --tag=ghcr.io/${{steps.repository.outputs.lowercase}}:${{github.sha}}
      - run: docker push ghcr.io/${{steps.repository.outputs.lowercase}}:${{github.sha}}